- hosts: all

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true

    - name: Install containerd
      ansible.builtin.apt:
        name: containerd
        state: latest
      become: true

    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: latest
      become: true

    - name: Build container image locally
      community.docker.docker_image:
        name: superlists
        source: build
        state: present
        build:
          path: ..
          platform: linux/amd64
        force_source: true
      delegate_to: 127.0.0.1

    - name: Export container image locally
      community.docker.docker_image:
        name: superlists
        archive_path: /tmp/superlists-img.tar
        source: local
      delegate_to: 127.0.0.1

    - name: Upload image to sever
      ansible.builtin.copy:
        src: /tmp/superlists-img.tar
        dest: /tmp/superlists-img.tar

    - name: Import container image on sever
      community.docker.docker_image:
        name: superlists
        load_path: /tmp/superlists-img.tar
        source: load
        force_source: true
        state: present
      become: true

    - name: Ensure .env file exists
      ansible.builtin.template:
        src: env.j2
        dest: "{{ ansible_env.HOME }}/superlists.env"
        force: false
      vars:
        host: "{{ inventory_hostname }}"
        secret_key: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"


    - name: Run container
      community.docker.docker_container:
        name: superlists
        image: superlists
        state: started
        recreate: true
        env_file: "{{ ansible_env.HOME }}/superlists.env"
        ports: 8080:8888
      become: true
